{{- range $name, $database := .Values.databases }}
{{- if $database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapiapp.databaseSecretName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "fastapiapp.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}-database
type: Opaque
stringData:
  POSTGRES_USER: {{ $database.username | quote }}
  POSTGRES_PASSWORD: {{ $database.password | quote }}
  POSTGRES_DB: {{ $database.name | quote }}
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s:5432/%s" $database.username $database.password (include "fastapiapp.databaseServiceName" (dict "root" $ "name" $name)) $database.name | quote }}
---
{{- end }}
{{- end }}
