environment: dev

imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false

services:
  movie:
    enabled: true
    repository: "docker.io/CHANGE_ME/jenkins-exam-movie-service"
    tag: "latest"
    replicaCount: 1
    pullPolicy: IfNotPresent
    port: 8000
    path: /api/v1/movies/openapi.json
    database: movie
    env:
      CAST_SERVICE_HOST_URL: http://cast-service:8000/api/v1/casts/
  cast:
    enabled: true
    repository: "docker.io/CHANGE_ME/jenkins-exam-cast-service"
    tag: "latest"
    replicaCount: 1
    pullPolicy: IfNotPresent
    port: 8000
    path: /api/v1/casts/openapi.json
    database: cast
    env:
      {}

databases:
  movie:
    enabled: true
    image: postgres:12.1-alpine
    storage: 1Gi
    username: movie_db_username
    password: movie_db_password
    name: movie_db_dev
  cast:
    enabled: true
    image: postgres:12.1-alpine
    storage: 1Gi
    username: cast_db_username
    password: cast_db_password
    name: cast_db_dev
